### ISSUE TITLE
Wallet Generation Action Creator

### ISSUE THREAD

**Issue by LuisOsta** [rapid-eth/rapid-playground#6]
**Is your feature request related to a problem? Please describe.**
There should be an action creator to generate and store a wallet for the user(for those not using metamask).

**Describe the solution you'd like**
The solution should use the ethers library to generate the wallet and store it in the provider. It should also utilize localStorage for medium-term usage of the wallet.

**Describe alternatives you've considered**
Requiring the user to have either metamask or a dApp browser.A clear and concise description of any alternative solutions or features you've considered.

**Comment by LuisOsta** [comment]
Implemented wallet generating that by default connects to JSON provider (ganache localhost). We need to add functionality to allow the user to set a custom provider and fallbacks

**Comment by kamescg** [comment]
I don't want to focus too much on wallet development generation stuff right now.

Let's put pause on this.
